[project]
name = "zebra_label_designer"
authors = [
    { name = "MARAND" }
]
description = "Visual Zebra ZPL label designer for ERPNext/Frappe"
requires-python = ">=3.10"
readme = "README.md"
license = { file = "license.txt" }
dynamic = ["version"]
dependencies = []

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
target-version = "py310"
